name: TypeScript CD in Render

on:
  # push:
  #   branches:
  #     - main
  workflow_run:
    workflows: ["TypeScript CI"]   # 👈 only run after CI
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # 👈 only if CI passed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Trigger Render Deploy
        run: |
          curl -X POST \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          --data '{"clearCache": false}' \
          ${{ secrets.RENDER_DEPLOY_HOOK }}
